attestation:
  host: https://test-as.sgx.trustedservices.intel.com/
  spid: 00000000000000000000000000000000
  apiKey: none
  acceptGroupOutOfDate: true
  disabled: true

control:
  listenHostPort: 127.0.0.1:31338

enclave:
  listenHostPort:       127.0.0.1:31337
  maxConnections:       128
  mrenclave:            libkbupd_enclave.hardened.debug
  debug:                true
  storageSize:          500000
  raftLogSize:          10485760
  maxBackupDataLength:  48
  electionTimeoutMs:    5000
  electionHeartbeats:   2
  replicationChunkSize: 0
  transferChunkSize:    0
  attestationExpiryCommitIntervalMs: 60000
  maxFrontendCount:     1
