#
# Azure Pipelines steps to run service/test/client_test.py
#

jobs:
- job: client_test
  displayName: client_test
  pool: client_test
  workspace:
    clean: all
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: kbupd
      targetPath: .
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: kbupctl
      targetPath: .
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: kbuptlsd
      targetPath: .
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: client_test
      targetPath: .
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: client_test_config
      targetPath: .
  - task: DownloadSecureFile@1
    name: ias_tls_config
    inputs:
      secureFile: kbuptlsd.intel-client.client_test.yml
  - task: DownloadSecureFile@1
    name: kbupd_enclave
    inputs:
      secureFile: enclave-a3baab19ef6ce6f34ab9ebb25ba722725ae44a8872dc0ff08ad6d83a9489de87-test.so

  - script: |
      chmod +x kbupd kbupctl kbuptlsd
    displayName: set up client_test

  - script: python3 client_test.py
    displayName:      client_test.py
    timeoutInMinutes: 30
    env:
      IAS_TLS_CONFIG: $(ias_tls_config.secureFilePath)
      IAS_SPID:       $(IAS_SPID)
      ENCLAVE_PATH:   $(kbupd_enclave.secureFilePath)
      ENCLAVE_DEBUG:  no
