#
# Azure Pipelines job to build the kbupd-builder docker image used to build backup service binaries inside.
#

jobs:
- job: docker_build_kbupd_builder
  displayName: docker build kbupd-builder
  pool:
    vmImage: ubuntu-18.04
  workspace:
    clean: all
  steps:
  - task: Docker@2
    displayName: docker login
    inputs:
      command:           login
      containerRegistry: signalbackupci-container-registry

  - script: docker pull signalbackupci.azurecr.io/signalbackupci:kbupd-builder || true
    displayName: docker pull

  - task: Docker@2
    displayName: docker build
    inputs:
      command:    build
      dockerfile: service/docker/Dockerfile
      arguments:  --build-arg UID=1000 --build-arg GID=1000 --cache-from signalbackupci.azurecr.io/signalbackupci:kbupd-builder
      repository: signalbackupci
      tags:       kbupd-builder

  - task: Docker@2
    displayName: docker push
    inputs:
      command:    push
      repository: signalbackupci
      tags:       kbupd-builder
