#
# Azure Pipelines job to build llvm-bolt from within in the kbupd-enclave-builder docker image.
#

jobs:
- job: make_llvm_bolt
  displayName: make llvm-bolt
  pool:
    vmImage: ubuntu-18.04
  container: kbupd-enclave-builder
  timeoutInMinutes: 120
  workspace:
    clean: all
  steps:
  - script: |
      cp -a enclave /home/rust/src && \
      mkdir enclave/build/ && \
      ln -s `pwd`/enclave/build /home/rust/src/build
    displayName: set up build directory

  - task: CacheBeta@1
    displayName: cached enclave/build/bin/
    inputs:
      path: enclave/build/bin/
      key:  enclave/docker/Dockerfile | enclave/docker/apt.conf | enclave/docker/sources.list | enclave/sgx_enclave.mk | "$(Build.SourceBranch)"
      restoreKeys:
        enclave/docker/Dockerfile | enclave/docker/apt.conf | enclave/docker/sources.list | enclave/sgx_enclave.mk | "refs/heads/$(System.PullRequest.TargetBranch)"

        enclave/docker/Dockerfile | enclave/docker/apt.conf | enclave/docker/sources.list | enclave/sgx_enclave.mk

  - script: make -C /home/rust/src/ llvm-bolt
    displayName: make llvm-bolt

  - publish:  enclave/build/bin/llvm-bolt
    artifact: llvm-bolt
