#
# Azure Pipelines job to build the insecure debug-mode enclave from within in the kbupd-enclave-builder docker image.
#

jobs:
- job: make_all_insecure
  displayName: make all FEATURES=insecure
  pool:
    vmImage: ubuntu-18.04
  container: kbupd-enclave-builder
  workspace:
    clean: all
  steps:
  - script: |
      cp -a enclave /home/rust/src && \
      mkdir enclave/build/ && \
      ln -s `pwd`/enclave/build /home/rust/src/build
    displayName: set up build directory

  - download: current
    artifact: llvm-bolt
  - script: install -D -m 755 $(Pipeline.Workspace)/llvm-bolt/llvm-bolt enclave/build/bin/llvm-bolt

  - script: make -C /home/rust/src/ bindgen
    displayName: make bindgen

  - script: make -C /home/rust/src/ all FEATURES=insecure
    displayName: make all FEATURES=insecure

  - publish:  enclave/build/libkbupd_enclave.unstripped.so
    artifact: insecure-libkbupd_enclave.unstripped.so
  - publish:  enclave/build/libkbupd_enclave.hardened.unstripped.so
    artifact: insecure-libkbupd_enclave.hardened.unstripped.so
  - publish:  enclave/build/libkbupd_enclave.hardened.unsigned.so
    artifact: insecure-libkbupd_enclave.hardened.unsigned.so
  - publish:  enclave/build/libkbupd_enclave.hardened.debug.so
    artifact: insecure-libkbupd_enclave.hardened.debug.so
  - publish:  enclave/build/libkbupd_enclave.hardened.signdata
    artifact: insecure-libkbupd_enclave.hardened.signdata
  - publish:  enclave/build/libkbupd_enclave.hardened.mrenclave
    artifact: insecure-libkbupd_enclave.hardened.mrenclave
